//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.22 at 05:43:50 PM ADT 
//


package org.ruleml.psoa.parser.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://psoa.ruleml.org/lang/spec#}PSOA"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oid",
    "op",
    "tupledi",
    "indterm",
    "slotdi"
})
@XmlRootElement(name = "Atom")
public class Atom {

    protected Oid oid;
    @XmlElement(required = true)
    protected Op op;
    @XmlElements({
        @XmlElement(name = "tup", type = Tup.class),
        @XmlElement(name = "tupdep", type = Tupdep.class)
    })
    protected List<Object> tupledi;
    @XmlElements({
        @XmlElement(name = "Ind", type = Ind.class),
        @XmlElement(name = "Rel", type = Rel.class),
        @XmlElement(name = "Var", type = Var.class),
        @XmlElement(name = "Expr", type = Expr.class),
        @XmlElement(name = "External", type = ExternalTERMType.class)
    })
    protected List<Object> indterm;
    @XmlElements({
        @XmlElement(name = "slot", type = Slot.class),
        @XmlElement(name = "slotdep", type = Slotdep.class)
    })
    protected List<Object> slotdi;

    /**
     * Gets the value of the oid property.
     * 
     * @return
     *     possible object is
     *     {@link Oid }
     *     
     */
    public Oid getOid() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Oid }
     *     
     */
    public void setOid(Oid value) {
        this.oid = value;
    }

    /**
     * Gets the value of the op property.
     * 
     * @return
     *     possible object is
     *     {@link Op }
     *     
     */
    public Op getOp() {
        return op;
    }

    /**
     * Sets the value of the op property.
     * 
     * @param value
     *     allowed object is
     *     {@link Op }
     *     
     */
    public void setOp(Op value) {
        this.op = value;
    }

    /**
     * Gets the value of the tupledi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tupledi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTUPLEDI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tup }
     * {@link Tupdep }
     * 
     * 
     */
    public List<Object> getTUPLEDI() {
        if (tupledi == null) {
            tupledi = new ArrayList<Object>();
        }
        return this.tupledi;
    }

    /**
     * Gets the value of the indterm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indterm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINDTERM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ind }
     * {@link Rel }
     * {@link Var }
     * {@link Expr }
     * {@link ExternalTERMType }
     * 
     * 
     */
    public List<Object> getINDTERM() {
        if (indterm == null) {
            indterm = new ArrayList<Object>();
        }
        return this.indterm;
    }

    /**
     * Gets the value of the slotdi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the slotdi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSLOTDI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Slot }
     * {@link Slotdep }
     * 
     * 
     */
    public List<Object> getSLOTDI() {
        if (slotdi == null) {
            slotdi = new ArrayList<Object>();
        }
        return this.slotdi;
    }

}
